# Generated by Django 5.2.17 on 2026-08-28 07:40

import apps.doctors.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('specialty', models.CharField(max_length=150, verbose_name='تخصص')),
                ('bio', models.TextField(verbose_name='معرفی')),
                ('profile_image', models.ImageField(upload_to='doctors/', validators=[apps.doctors.validators.validate_image_size, apps.doctors.validators.validate_image_extension], verbose_name='تصویر پروفایل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='portfolio/', validators=[apps.doctors.validators.validate_image_size, apps.doctors.validators.validate_image_extension], verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='doctors.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'نمونه\u200cکار',
                'verbose_name_plural': 'نمونه\u200cکارها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='doctors.doctor', verbose_name='پزشک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_permissions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مدیر پزشک',
                'verbose_name_plural': 'مدیران پزشک',
                'constraints': [models.UniqueConstraint(fields=('user', 'doctor'), name='unique_user_doctor')],
            },
        ),
    ]
